# Generated by Django 3.2.7 on 2021-09-23 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='usuario',
        ),
    ]
